### ISSUE TITLE
Use rusb (libusb) or nusb instead of JNI calls

### ISSUE THREAD

**Issue by dgramop** [wuwbobo2021/android-usbser-rs#1]
In the TODO list README, you have the following item. I just wanted to make an issue so that we could track it
- Currently, the usb module handles everything with JNI calls. libusb and its wrapper rusb have limited functionalities on unrooted Android, without being able to check for connected devices before opening one of them. Even in android-usbser-rs, create_rusb_connection() needs debugging.

This will help us with performance while actively communicating with the device. 

I've written several USB drivers for Android, including native drivers. libusb does work on an unrooted android, but it does not have enough permissions to scan for devices. Instead, we must open a device through android's APIs (get permissions too), then pass the file descriptor down into native code. This strategy is sound for rusb (and I'm sure also nusb will work too).

Anyhow I'm happy to help out with this implementation. Can you assign this issue to me? Thanks for you work on this repo :)

**Comment by wuwbobo2021** [comment]
`libusb_wrap_sys_device()` currently fails on my devices (currently I'm not giving root permission to the test application). 

See `README.md` for preparing the building environment. Test code:

`Cargo.toml`:

```toml
[package]
name = "android-rusb-test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
log = "0.4"
android_logger = "0.14"
android-activity = { version = "0.6", features = ["native-activity"] }
android-usbser = { version = "0.1.1", features = ["unsafe-rusb"] }

[lib]
name = "android_rusb_test"
crate-type = ["cdylib"]
path = "android_rusb_test.rs"

[package.metadata.android]
package = "com.example.android_rusb_test"
build_targets = [ "aarch64-linux-android" ]

[package.metadata.android.sdk]
min_sdk_version = 16
target_sdk_version = 30

[[package.metadata.android.uses_feature]]
name = "android.hardware.usb.host"
required = true
```

`android_rusb_test.rs`:

```rust
use android_activity::{AndroidApp, MainEvent, PollEvent};
use android_usbser::usb;

#[no_mangle]
fn android_main(app: AndroidApp) {
    // TODO: `println` or `eprintln` macro must be used prior to any direct `libusb` call,
    // even if `android_logger` is preferred. Otherwise it `create_rusb_context()` will crash
    // while calling `libusb`. It might be fixed by putting `println` inside this function.
    //
    // `adb logcat <app_name>:D '*:S'` is for macros from `log` backed by `android_logger`;
    // `adb logcat RustStdoutStderr:D '*:S'` is for `println` or `eprintln`.
    let mut permitted_device = None;
    let mut on_destroy = false;
    loop {
        app.poll_events(
            Some(std::time::Duration::from_secs(1)), // timeout
            |event| match event {
                PollEvent::Main(MainEvent::Resume { loader: _, .. }) => {
                    println!("Main Resume.");
                    let usb_devs = usb::list_devices().unwrap();
                    if let Some(dev) = usb_devs.into_iter().next() {
                        if !dev.has_permission().unwrap_or(false) {
                            let _ = dev.request_permission();
                        } else {
                            permitted_device.replace(dev);
                        }
                    }
                }
                PollEvent::Main(MainEvent::Destroy) => {
                    println!("Main Destroy.");
                    on_destroy = true;
                }
                _ => (),
            },
        );
        if on_destroy {
            return;
        }
        if let Some(dev) = permitted_device.take() {
            println!("opening device {}", dev.path_name());
            let conn = dev.open_device().unwrap();
            println!("open_device() success.");
            unsafe {
                println!("before create_rusb_context().");
                if let Ok(mut ctx) = usb::create_rusb_context() {
                    println!("create_rusb_context() success.");
                    match conn.create_rusb_connection(&mut ctx) {
                        Ok(_) => {
                            println!("Success!"); // desired
                            return; // exit on success
                        }
                        Err(e) => eprintln!("Error: {e}"),
                    }
                }
            }
        }
    }
}
```

Log:

```
adb logcat RustStdoutStderr:D '*:S'
--------- beginning of crash
--------- beginning of system
--------- beginning of main
11-07 19:37:53.637 21286 21299 I RustStdoutStderr: Main Resume.
11-07 19:37:55.283 21286 21299 I RustStdoutStderr: Main Resume.
11-07 19:37:56.196 21286 21299 I RustStdoutStderr: Main Resume.
11-07 19:37:56.202 21286 21299 I RustStdoutStderr: opening device /dev/bus/usb/001/009
11-07 19:37:56.206 21286 21299 I RustStdoutStderr: open_device() success.
11-07 19:37:56.206 21286 21299 I RustStdoutStderr: before create_rusb_context().
11-07 19:37:56.206 21286 21299 I RustStdoutStderr: create_rusb_context() success.
11-07 19:37:56.206 21286 21299 I RustStdoutStderr: before libusb_wrap_sys_device(). fd: 0x0000001c
11-07 19:37:56.206 21286 21299 I RustStdoutStderr: [timestamp] [threadID] facility level [function call] <message>
11-07 19:37:56.206 21286 21299 I RustStdoutStderr: --------------------------------------------------------------------------------
11-07 19:37:56.206 21286 21299 I RustStdoutStderr: [ 0.000517] [00005334] libusb: debug [libusb_wrap_sys_device] wrap_sys_device 0x7f940c6eec
11-07 19:37:56.206 21286 21299 I RustStdoutStderr: [ 0.000552] [00005334] libusb: debug [linux_get_device_address] getting address for device: (null) detached: 1
11-07 19:37:56.206 21286 21299 I RustStdoutStderr: [ 0.000563] [00005334] libusb: error [op_wrap_sys_device] connectinfo failed, errno=9
11-07 19:37:56.206 21286 21299 I RustStdoutStderr: [ 0.000571] [00005334] libusb: debug [libusb_wrap_sys_device] wrap_sys_device 0x7f940c6eec returns -1
11-07 19:37:56.206 21286 21299 I RustStdoutStderr: Error: Input/Output Error
11-07 19:37:56.206 21286 21299 I RustStdoutStderr: [ 0.000586] [00005334] libusb: debug [libusb_exit]  
11-07 19:37:56.206 21286 21299 I RustStdoutStderr: [ 0.000594] [00005334] libusb: debug [usbi_remove_event_source] remove fd 31
11-07 19:37:56.206 21286 21299 I RustStdoutStderr: [ 0.000608] [00005334] libusb: debug [usbi_remove_event_source] remove fd 30
```

(Another problem: it calls `dev.request_permission()` for double times before `dev.has_permission()` returns true.)
