### ISSUE TITLE
The 1st example crashes when permission request is accepted: `ActivityManager: freezing 4327 com.example.android_usb_cdc_test`

### ISSUE THREAD

**Issue by zpg6** [wuwbobo2021/android-usbser-rs#5]
Really, really cool repo! But can't seem to get it to actually connect to device because of a SecurityException.

```
01-01 17:59:21.937 17125 17157 I android_usb_cdc_test: android_usb_cdc_test: 🟢 Polling events...
01-01 17:59:22.940 17125 17157 I android_usb_cdc_test: android_usb_cdc_test: 🟢 Polling events...
01-01 17:59:23.940 17125 17157 I android_usb_cdc_test: android_usb_cdc_test: 🟢 Polling events...
01-01 17:59:24.942 17125 17157 I android_usb_cdc_test: android_usb_cdc_test: 🟢 Polling events...
01-01 17:59:25.947 17125 17157 I android_usb_cdc_test: android_usb_cdc_test: 🟢 Polling events...
01-01 17:59:26.948 17125 17157 I android_usb_cdc_test: android_usb_cdc_test: 🟢 Polling events...
01-01 17:59:27.967 17125 17157 W android_usb_cdc_test: jni_min_helper: Exception in thread "ThreadId(2)" java.lang.SecurityException: User has not given 10262/com.example.android_usb_cdc_test permission to access device /dev/bus/usb/002/002
01-01 17:59:28.008 17125 17157 W android_usb_cdc_test: jni_min_helper: 
01-01 17:59:28.008 17125 17157 W android_usb_cdc_test:    0: std::backtrace::Backtrace::create
01-01 17:59:28.008 17125 17157 W android_usb_cdc_test:    1: jni_min_helper::print_rust_stack
01-01 17:59:28.008 17125 17157 W android_usb_cdc_test:    2: core::ops::function::FnOnce::call_once
01-01 17:59:28.008 17125 17157 W android_usb_cdc_test:    3: android_usbser::usb_info::DeviceInfo::build
01-01 17:59:28.008 17125 17157 W android_usb_cdc_test:    4: android_usbser::usb_conn::get_extra_device
01-01 17:59:28.008 17125 17157 W android_usb_cdc_test:    5: <android_usbser::usb_conn::HotplugWatch as futures_core::stream::Stream>::poll_next
01-01 17:59:28.008 17125 17157 W android_usb_cdc_test:    6: futures_lite::future::block_on
01-01 17:59:28.008 17125 17157 W android_usb_cdc_test:    7: android_usbser::usb_conn::HotplugWatch::take_next
01-01 17:59:28.008 17125 17157 W android_usb_cdc_test:    8: android_main
01-01 17:59:28.008 17125 17157 W android_usb_cdc_test:    9: std::sys::backtrace::__rust_begin_short_backtrace
01-01 17:59:28.008 17125 17157 W android_usb_cdc_test:   10: core::ops::function::FnOnce::call_once{{vtable.shim}}
01-01 17:59:28.008 17125 17157 W android_usb_cdc_test:   11: std::sys::pal::unix::thread::Thread::new::thread_start
01-01 17:59:28.008 17125 17157 W android_usb_cdc_test:   12: _ZL15__pthread_startPv
01-01 17:59:28.008 17125 17157 W android_usb_cdc_test:   13: __start_thread
01-01 17:59:28.009 17125 17157 I android_usb_cdc_test: android_usb_cdc_test: 🟢 Device connected (/dev/bus/usb/002/002).
01-01 17:59:28.018 17125 17157 W android_usb_cdc_test: jni_min_helper: Exception in thread "ThreadId(2)" java.lang.SecurityException: User has not given 10262/com.example.android_usb_cdc_test permission to access device /dev/bus/usb/002/002
01-01 17:59:28.022 17125 17157 W android_usb_cdc_test: jni_min_helper: 
01-01 17:59:28.022 17125 17157 W android_usb_cdc_test:    0: std::backtrace::Backtrace::create
01-01 17:59:28.022 17125 17157 W android_usb_cdc_test:    1: jni_min_helper::print_rust_stack
01-01 17:59:28.022 17125 17157 W android_usb_cdc_test:    2: core::ops::function::FnOnce::call_once
01-01 17:59:28.022 17125 17157 W android_usb_cdc_test:    3: android_usbser::usb_info::DeviceInfo::build
01-01 17:59:28.022 17125 17157 W android_usb_cdc_test:    4: android_usbser::usb_info::list_devices
01-01 17:59:28.022 17125 17157 W android_usb_cdc_test:    5: android_usbser::usb_conn::<impl android_usbser::usb_info::DeviceInfo>::request_permission
01-01 17:59:28.022 17125 17157 W android_usb_cdc_test:    6: android_main
01-01 17:59:28.022 17125 17157 W android_usb_cdc_test:    7: std::sys::backtrace::__rust_begin_short_backtrace
01-01 17:59:28.022 17125 17157 W android_usb_cdc_test:    8: core::ops::function::FnOnce::call_once{{vtable.shim}}
01-01 17:59:28.022 17125 17157 W android_usb_cdc_test:    9: std::sys::pal::unix::thread::Thread::new::thread_start
01-01 17:59:28.022 17125 17157 W android_usb_cdc_test:   10: _ZL15__pthread_startPv
01-01 17:59:28.022 17125 17157 W android_usb_cdc_test:   11: __start_thread
01-01 17:59:28.024 17125 17157 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10262; state: ENABLED
01-01 17:59:28.024 17125 17157 D CompatibilityChangeReporter: Compat change id reported: 236704164; UID 10262; state: ENABLED
```

### I am using this as my Cargo.toml to run it

Tired several Android SDK versions between 29-35. I also tried to use your PR branch on `cargo-apk` library (https://github.com/rust-mobile/cargo-apk/pull/67), and tried with and without `value = "true"`.

```toml
[package]
name = "android-usb-cdc-test"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "dylib"]

[package.metadata.android.signing.release]
path = "release.keystore"
keystore_password = "<redacted>"

[dependencies]
log = "0.4"
android_logger = "0.14"
android-activity = { version = "0.6", features = ["native-activity"] }
android-usbser = "0.2.1"
serialport = "4.6"

[package.metadata.android]
package = "com.example.android_usb_cdc_test"
build_targets = [ "aarch64-linux-android" ]
resources = "./res"

[package.metadata.android.sdk]
min_sdk_version = 16
target_sdk_version = 30

[[package.metadata.android.uses_feature]]
name = "android.hardware.usb.host"
required = true

[[package.metadata.android.application.activity.intent_filter]]
actions = ["android.hardware.usb.action.USB_DEVICE_ATTACHED"]

# Please check <https://github.com/rust-mobile/cargo-apk/pull/67> if it fails.
# Otherwise comment out the lines below (request for permission purely at runtime).
[[package.metadata.android.application.activity.meta_data]]
name = "android.hardware.usb.action.USB_DEVICE_ATTACHED"
resource = "@xml/device_filter"
value = "true"

[[package.metadata.android.uses_permission]]
name = "android.permission.USB_PERMISSION"
max_sdk_version = 15

[[package.metadata.android.uses_feature]]
name = "android.hardware.usb.host"
required = true
```
